<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><?php echo App::config("nazivApp") ?></title>
<link rel="stylesheet" href="<?php echo App::config("url") ?>public/css/foundation.css">

<link rel="stylesheet" href="<?php echo App::config("url") ?>public/css/app.css">
<link href="<?php echo App::config("url") ?>public/css/css/all.css" rel="stylesheet">
<link rel="apple-touch-icon" sizes="180x180" href="<?php echo App::config("url") ?>public/css/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="<?php echo App::config("url") ?>public/css/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="<?php echo App::config("url") ?>public/css/favicon-16x16.png">
<link rel="manifest" href="<?php echo App::config("url") ?>public/css/site.webmanifest">