

<div class="grid-container">
    <div class="grid-x" style="text-align:center;">
        <div class="large-3 medium-3 small-3 columns">
        </div>

        <div class="large-12 medium-12 small-12 columns" >
            <h3>URANIA REZERVACIJE</h3>
            <p>interna web aplikacija Kinematografa Osijek za rezervaciju sjedala za različite evente</p>
        </div>

        <div class="large-3 medium-3 small-3 columns">
        </div>
    </div>
        
        
    <div class="grid-x">
        <div class="large-3 medium-3 small-3 columns">
        </div>

        <div class="large-12 medium-12 small-12 columns">
        <img src="<?php echo App::config("url")."public/css/urania.jpg" ?>" alt="Logo">
        </div>
        
        <div class="large-3 medium-3 small-3 columns">
        </div>
    </div>
</div>