<div class="grid-container">
    <div class="grid-x" style="text-align:center;">
        <div class="large-3 medium-3 small-3 columns">
            </div>

        <div class="large-12 medium-12 small-12 columns">
            <h3>O nama</h3>
            <br />
            <p>Kinematografi Osijek d.d. su trgovačko društvo registrirano u Osijeku koje se bavi kino prikazivačkom
                djelatnošću. (nac. klasifikacija djelatnosti 92.130). Društvo raspolaže s dvije atraktivne zgrade- kinom
                Urania i kinom Europa, obje zaštićene kao spomenici kulture s dugom povješću i tradicijom prikazivanja
                filmova.</p>
            <br />
            <p>Kinematografi Osijek član su prestižne europske kinoprikazivačke grupacije EUROPA CINEMAS i kao takvi
                imaju otvoren pristup programima EU - MEDIA, odnosno EURIMAGES.</p>
            <br />
            <br />
            <h3>Osnovni i kontakt podaci</h3>
            <br />
            <p><strong>Kinematografi Osijek d.d., Osijek, Hrvatska</strong></p>
            <p>Šetalište kardinala Franje Šepera 8</p>
            <p>Tel/fax: 031/ 205 501 – od 8:00 do 16:00</p>
            <br />
            <p>OIB: 40405502802</p>
            <p>MBS 03014363</p>
            <p>Osoba ovlaštena za zastupanje: mr.sc. Marijana Bošnjak direktor/predsjednik Uprave</p>
            <br />
            <br />
            <p><strong>Kino Urania</strong></p>
            <p>Vjekoslava Hengla 1</p>
            <p>031/ 205 507 – od 17:00 do 23:00</p>
            <br />
            <br />
            <p><strong>E-mail</strong></p>
            <p>info@kinematografi-osijek.hr</p>
            <p>ulaznice@kinematografi-osijek.hr</p>
            <p>skole@kinematografi-osijek.hr</p>
            </div>

        <div class="large-3 medium-3 small-3 columns">
            </div>
    </div>
</div>