<div class="grid-container">
    <div class="grid-x" style="text-align:center;">
        <div class="large-3 medium-3 small-3 columns">
        </div>

        <div class="large-12 medium-12 small-12 columns">
            <h3>Upute za unos rezervacije</h3>
            <br />
            <br />
            <ol>
                <li>Prijviti se na stranicu s korisničkim imenom i lozinkom jednog od administratora</li>
                <li>Kreirati događaj</li>
                <li>Dodati gledatelja s njegovim kontakt podacima u bazu</li>
                <li>Klikom na događaj odabrati opciju "Rezerviraj sjedala"</li>
                <li>Klik na odabrano sjedalo nudi opciju dodavanja gledatelja</li>
                <li>Nakon odabira gledatelja za unos rezervacije kliknuti "Spremi"</li>
            </ol>
        </div>

        <div class="large-3 medium-3 small-3 columns">
        </div>
    </div>
</div>