<label>Ime
    <input type="text" name="ime" 
    value="<?php echo Request::post("ime") ?>" />
  </label>

  <label>Prezime
    <input type="text" name="prezime"
    value="<?php echo Request::post("prezime") ?>" />
  </label>

  <label>E-mail
    <input type="email" name="eMail"
    value="<?php echo Request::post("eMail") ?>" />
  </label>

  <label>Telefon
    <input type="text" name="telefon"
    value="<?php echo Request::post("telefon") ?>" />
  </label>

  <label>GDPR
    <input type="text" name="gdpr"
    value="<?php echo Request::post("gdpr") ?>" />
  </label>
 
  <label>Napomena
    <input type="text" name="napomena"
    value="<?php echo Request::post("napomena") ?>" />
  </label>



  <label>
    <input type="hidden" name="sifra"
    value="<?php echo Request::post("sifra") ?>" />
  </label>