<label>Vrsta
    <input type="text" name="vrsta" 
    value="<?php echo Request::post("vrsta") ?>" />
  </label>

  <label>Naziv
    <input type="text" name="naziv"
    value="<?php echo Request::post("naziv") ?>" />
  </label>

  <label>Izvođač
    <input type="text" name="izvodac"
    value="<?php echo Request::post("izvodac") ?>" />
  </label>

  <label>Termin
    <input type="datetime" name="termin" 
    value="<?php echo Request::post("termin") ?>" />
  </label>

  <label>Organizator
    <input type="text" name="organizator"
    value="<?php echo Request::post("organizator") ?>" />
  </label>

  <label>Administrator
    <input type="text" name="administrator"
    value="<?php echo Request::post("administrator") ?>" />
  </label>

  <label>Slika
    <input type="file" name="slika"  />
  </label>
