<?php 
  $head = "<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">";

 $js="
 <script>
 let sifraSjedalo = '$sjedalo';
 let sifraDogadaj = '$dogadaj'; </script>
 <script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>
 <script>
 var putanja=\"" . APP::config("url") .  "\";


 </script>
 <script src=\"" . APP::config("url") . "public/js/sjedala/edit.js\"></script>";
?>


<div class="large-6 columns" style="text-align: center">
    <?php foreach ($naziv as $key => $value) {
  foreach ($value as $key1 ) {
  echo "<h4>" . $key1 . "</h4><br/>";
  }              
         
}
?>
</div>

<div class="large-6 columns" style="text-align: center">
    <br />
    <h5>Rezervacija na ime:</h5>

    <?php if($gledatelj==null){
            echo "Mjesto je slobodno, zapiši rezervaciju";
            } else
            {
            foreach ($gledatelj as $gledatelji) {
      
                    echo $gledatelji["ime"] . " " . $gledatelji["prezime"];
                    echo "<br />";
                    echo $gledatelji["telefon"];
                    echo "<br />";
                    echo $gledatelji["eMail"];
                    $sifra = $gledatelji["sifra"];  
                    }
            }
            ?>

</div>

<br />

<form class="log-in-form" method="post" action="<?php echo App::config("url") ?>sjedalo/delete/">

            <label>
                <input type="hidden" name="sjedalo" value="<?php echo $sjedalo; ?>" />
            </label>

            <label>
                <input type="hidden" name="dogadaj" value="<?php echo $dogadaj; ?>" />
            </label>


            <div class="grid-x">
                <div class="large-4 columns">
                </div>
                <div class="large-12 columns" style="overflow: auto; max-height: 400px;">
                    <div class="callout">
                        Traži gledatelja
                        <input type="text" id="uvjet" name="gledatelj" />

                    </div>
                </div>
                <div class="large-4 columns">
                </div>
            </div>


                <div class="grid-x">
                    <div class="large-6 columns" style="padding: 10px;">
                        <a href="<?php echo App::config("url") ?>gledatelj/prepareadd" class="button expanded">
                            Novi gledatelj
                        </a>
                    </div>
                    <div class="large-6 columns" style="padding: 10px;">
                        <a href="<?php echo App::config("url") ?>sjedalo/index/<?php echo $dogadaj ?>"
                            class="success button expanded">
                            Spremi
                        </a>
                    </div>
                    <div class="large-6 columns" style="padding: 10px;">
                        <input type="submit" class="alert button expanded" value="Obriši rezervaciju" />
                    </div>
                </div>


            
</form>